### PR TITLE
Update links for Jonas & der Wolf

### PR DESCRIPTION
**Pull request by MRigal**

### CODE REVIEW

**Comment by MRigal** [comment]
I wasn't sure if the proof needs to be linking to jobs or not. This is why I proposed to link to our membership of the Django Software Foundation. Else it can be restored to https://www.creative-city-berlin.de/de/search/?q=django+jonas&t=job&submit=Suche which will point to actuall job offerings

**Review by MrtnBckr — APPROVED** [review]
Looks good to me.

**Review by hartwork — APPROVED** [review]
@MRigal good to see you, it's been a while :smiley:
I'm happy to apply those updates :+1:

**Comment by MRigal** [comment]
Hi Sebastian!
Sorry I hadn't even realized you owned this repository! Great job!
It's been a while indeed! I hope there will be some new gathering possibilities in the future!
Best, Matthieu

**Comment by hartwork** [comment]
No worries, me too. See you!

**Pull request merged**
